require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SporePrintsController do

  # This should return the minimal set of attributes required to create a valid
  # SporePrint. As you add validations to SporePrint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SporePrintsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all spore_prints as @spore_prints" do
      spore_print = SporePrint.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:spore_prints)).to eq([spore_print])
    end
  end

  describe "GET show" do
    it "assigns the requested spore_print as @spore_print" do
      spore_print = SporePrint.create! valid_attributes
      get :show, {:id => spore_print.to_param}, valid_session
      expect(assigns(:spore_print)).to eq(spore_print)
    end
  end

  describe "GET new" do
    it "assigns a new spore_print as @spore_print" do
      get :new, {}, valid_session
      expect(assigns(:spore_print)).to be_a_new(SporePrint)
    end
  end

  describe "GET edit" do
    it "assigns the requested spore_print as @spore_print" do
      spore_print = SporePrint.create! valid_attributes
      get :edit, {:id => spore_print.to_param}, valid_session
      expect(assigns(:spore_print)).to eq(spore_print)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SporePrint" do
        expect {
          post :create, {:spore_print => valid_attributes}, valid_session
        }.to change(SporePrint, :count).by(1)
      end

      it "assigns a newly created spore_print as @spore_print" do
        post :create, {:spore_print => valid_attributes}, valid_session
        expect(assigns(:spore_print)).to be_a(SporePrint)
        expect(assigns(:spore_print)).to be_persisted
      end

      it "redirects to the created spore_print" do
        post :create, {:spore_print => valid_attributes}, valid_session
        expect(response).to redirect_to(SporePrint.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved spore_print as @spore_print" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(SporePrint).to receive(:save).and_return(false)
        post :create, {:spore_print => { "name" => "invalid value" }}, valid_session
        expect(assigns(:spore_print)).to be_a_new(SporePrint)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(SporePrint).to receive(:save).and_return(false)
        post :create, {:spore_print => { "name" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested spore_print" do
        spore_print = SporePrint.create! valid_attributes
        # Assuming there are no other spore_prints in the database, this
        # specifies that the SporePrint created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(SporePrint).to receive(:update).with({ "name" => "MyString" })
        put :update, {:id => spore_print.to_param, :spore_print => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested spore_print as @spore_print" do
        spore_print = SporePrint.create! valid_attributes
        put :update, {:id => spore_print.to_param, :spore_print => valid_attributes}, valid_session
        expect(assigns(:spore_print)).to eq(spore_print)
      end

      it "redirects to the spore_print" do
        spore_print = SporePrint.create! valid_attributes
        put :update, {:id => spore_print.to_param, :spore_print => valid_attributes}, valid_session
        expect(response).to redirect_to(spore_print)
      end
    end

    describe "with invalid params" do
      it "assigns the spore_print as @spore_print" do
        spore_print = SporePrint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(SporePrint).to receive(:save).and_return(false)
        put :update, {:id => spore_print.to_param, :spore_print => { "name" => "invalid value" }}, valid_session
        expect(assigns(:spore_print)).to eq(spore_print)
      end

      it "re-renders the 'edit' template" do
        spore_print = SporePrint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(SporePrint).to receive(:save).and_return(false)
        put :update, {:id => spore_print.to_param, :spore_print => { "name" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested spore_print" do
      spore_print = SporePrint.create! valid_attributes
      expect {
        delete :destroy, {:id => spore_print.to_param}, valid_session
      }.to change(SporePrint, :count).by(-1)
    end

    it "redirects to the spore_prints list" do
      spore_print = SporePrint.create! valid_attributes
      delete :destroy, {:id => spore_print.to_param}, valid_session
      expect(response).to redirect_to(spore_prints_url)
    end
  end

end
